[package]
name = "waila-cli"
description = "What am I looking at? - parser for bitcoin strings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin-waila = "0.1.3"
clap = { version = "4.1.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitcoin = { version = "0.29.2", default-features = false }
lightning-invoice = { version = "0.22.0", default-features = false, features = ["serde"] }
lnurl-rs = { version = "0.2.1", default-features = false }
#lightning = { version = "0.0.114", default-features = false }

